#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=03:00:00
#SBATCH --mem=2G
#SBATCH -C intel18
#SBATCH -J Genotypes
#SBATCH -o Genotypes.o%j

#=====================================================================
# This script runs: Genotypes.R
# Submited on: Fri Jan 11 09:54:15 EST 2019
#=====================================================================

# Work Directory
cd /mnt/research/NMDL/MFM_WB/Genotypes

# Run R Code
R -e 'library("knitr");knitr::spin ("Genotypes.R")'

# Add metadata to md file
cat .metadata Genotypes.md > tmp; mv tmp Genotypes.md

# Render HTML
R -e 'library("prettydoc");rmarkdown::render ("Genotypes.md")'

# Job Details
echo Job Details
scontrol show job $SLURM_JOB_ID
